"""initial schema

Revision ID: 1131a65c8194
Revises: 
Create Date: 2026-02-25 22:16:05.067683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1131a65c8194'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_tcg_id', sa.String(length=50), nullable=False),
    sa.Column('tcgplayer_product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('set_name', sa.String(length=200), nullable=False),
    sa.Column('set_code', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('supertype', sa.String(length=50), nullable=False),
    sa.Column('image_small', sa.String(length=500), nullable=True),
    sa.Column('image_large', sa.String(length=500), nullable=True),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('hp', sa.String(length=10), nullable=True),
    sa.Column('types_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_pokemon_tcg_id'), 'cards', ['pokemon_tcg_id'], unique=True)
    op.create_index(op.f('ix_cards_tcgplayer_product_id'), 'cards', ['tcgplayer_product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('variant', sa.String(length=30), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_card_date', 'price_history', ['card_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_price_history_card_id'), 'price_history', ['card_id'], unique=False)
    op.create_index(op.f('ix_price_history_recorded_at'), 'price_history', ['recorded_at'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('variant', sa.String(length=30), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('mid_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('listing_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'marketplace', 'condition', 'variant', name='uq_price_source')
    )
    op.create_index(op.f('ix_prices_card_id'), 'prices', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_card_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_price_history_recorded_at'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_card_id'), table_name='price_history')
    op.drop_index('ix_price_history_card_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_cards_tcgplayer_product_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_pokemon_tcg_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
